# Generated by Django 5.0.7 on 2024-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=50)),
                ('parentmob', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=20)),
                ('joindate', models.DateField()),
            ],
        ),
    ]
