# Generated by Django 5.0.7 on 2024-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='stream',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('Microsoft', 8000), ('Tally', 6000), ('Programming', 7300)], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='parentmob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='scheme',
            field=models.CharField(choices=[('General', 10), ('Referal', 40), ('Walkin', 80)], max_length=10),
        ),
    ]
