# Generated by Django 5.0.7 on 2024-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enquiry_stream_alter_enquiry_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='qualification',
            field=models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], max_length=50),
        ),
    ]
