# Generated by Django 5.0.7 on 2024-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enquiry_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(max_length=30)),
                ('qualification', models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], default=None, max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[(8000, 'microsoft'), (7000, 'Tally'), (6000, 'webdevelopment')], default=None, max_length=50)),
                ('scheme', models.CharField(choices=[(10, 'referal'), (30, 'walking')], default=None, max_length=50)),
                ('parent_mobile_number', models.CharField(max_length=10)),
                ('register_number', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
