# Generated by Django 5.0.7 on 2024-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_formdetails_delete_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('qualification', models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], max_length=50)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(choices=[(6000, 'Microsoft'), (8000, 'Tally'), (10000, 'Programming')], max_length=20)),
                ('scheme', models.CharField(choices=[(10, 'General'), (40, 'Referal'), (80, 'walking')], max_length=10)),
                ('parentmob', models.CharField(max_length=10)),
                ('regno', models.CharField(max_length=20)),
                ('joindate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='FormDetails',
        ),
    ]
