# Generated by Django 5.0.7 on 2024-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enquiry_delete_formdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[(6000, 'Microsoft'), (8000, 'Tally'), (10000, 'Programming')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='qualification',
            field=models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='scheme',
            field=models.CharField(choices=[(10, 'General'), (40, 'Referal'), (80, 'walking')], default=None, max_length=10),
        ),
    ]
