# Generated by Django 5.0.7 on 2024-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_enquiry_course_alter_enquiry_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[(6000, 'Microsoft'), (8000, 'Tally'), (10000, 'Programming')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='scheme',
            field=models.CharField(choices=[(10, 'General'), (40, 'Referal'), (80, 'walking')], default=None, max_length=10, null=True),
        ),
    ]
