# Generated by Django 5.0.7 on 2024-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_enquiry_course_alter_enquiry_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='qualification',
            field=models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
