# Generated by Django 5.0.7 on 2024-08-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_enquiry_enquiryform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnquiryForm',
            new_name='Enquiry',
        ),
    ]
