# Generated by Django 5.0.7 on 2024-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_enquiryform_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='stream',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
