# Generated by Django 5.0.7 on 2024-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_enquiry_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='stream',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
