# Generated by Django 5.0.7 on 2024-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_enquiry_whatsapp_alter_enquiry_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
